### ISSUE TITLE
3.2 fails to build with Qt 5.9.5

### ISSUE THREAD

**Issue by mc4man** [flaviotordini/minitube#151]
Trying on Ubuntu 18.04, build succeeds on 19.10 with Qt 5.12, git pages claims needing just Qt >= 5.6 

```src/ytvideo.cpp: In lambda function:
src/ytvideo.cpp:106:38: error: no match for ‘operator[]’ (operand types are ‘const QJsonValue’ and ‘const char [5]’)
                     int itag = format["itag"].toInt();
                                      ^
src/ytvideo.cpp:107:41: error: no match for ‘operator[]’ (operand types are ‘const QJsonValue’ and ‘const char [4]’)
                     QString url = format["url"].toString();
                                         ^
src/ytvideo.cpp:109:48: error: no match for ‘operator[]’ (operand types are ‘const QJsonValue’ and ‘const char [7]’)
                         QString cipher = format["cipher"].toString();```

**Comment by enigma9o7** [comment]
Same issue here on 32-bit LTS... I can make 3.1 using mc4man ppa, but 3.2 fails with those operator [] errors.  

Flavio, if you're reading this, I love this app for my kids computers, but wished you would package for long-term-support version, which I imagine the majority of people use; those that do use newer versions probably can use  packages from the latest LTS anyway.  It would make it more accessible to more people and avoid these make/build issues...

**Comment by flaviotordini** [comment]
5.6 is surely wrong and will be fixed in the docs. I'll have a look and what is the minimum Qt version required. That [] operator has been introduced in 5.10. So at least you need 5.10.
