### ISSUE TITLE
build error ‘class QFileInfo’ has no member named ‘birthTime’

### ISSUE THREAD

**Issue by Mikhail22** [flaviotordini/minitube#199]
I am trying to build on a 32-bit pc, Ubuntu 18.04.5 LTS i686
Installed dependencies with the command from the readme.md, then did ```qmake -makefile``` then ```make```.
I get this error:   
```
g++ -c -pipe -O3 -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=3.8.2 -DAPP_NAME=Minitube -DAPP_UNIX_NAME=minitube -DAPP_SNAPSHOT -DQT_NO_DEBUG_OUTPUT -DQT_USE_QSTRINGBUILDER -DQT_STRICT_ITERATORS -DQT_DEPRECATED_WARNINGS -DHTTP -DMEDIA_MPV -DAPP_LINUX -DDATADIR=\"/usr/share\" -DPKGDATADIR=\"/usr/share/minitube\" -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Ilib/http/src -Ilib/idle/src -Ilib/js -Ilib/media/src -Ilib/media/src/mpv -Isrc/qtsingleapplication -Isrc/yt -Isrc/yt/invidious -Isrc/yt/ytjs -Isrc -Ilocale -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtX11Extras -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtQml -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtDBus -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Ibuild/moc -isystem /usr/include/libdrm -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -o build/obj/lib/http/src/localcache.o lib/http/src/localcache.cpp
lib/http/src/localcache.cpp: In member function ‘bool LocalCache::isCached(const QString&)’:
lib/http/src/localcache.cpp:45:55: error: ‘class QFileInfo’ has no member named ‘birthTime’
                   (maxSeconds == 0 || QFileInfo(path).birthTime().secsTo(
                                                       ^~~~~~~~~
lib/http/src/localcache.cpp: In member function ‘void LocalCache::expire()’:
lib/http/src/localcache.cpp:135:32: error: ‘class QFileInfo’ has no member named ‘birthTime’
         cacheItems.insert(info.birthTime(), path);
                                ^~~~~~~~~
Makefile:2401: recipe for target 'build/obj/lib/http/src/localcache.o' failed
make: *** [build/obj/lib/http/src/localcache.o] Error 1

```

**Comment by thewolfwillcome** [comment]
Your Qt version ist too old. minitube min Qt version is 5.12 the birthTime property was introduced in Qt 5.10.
Pay attention to the version numbers in the Build instructions of the README.md

**Comment by Mikhail22** [comment]
> Your Qt version ist too old. minitube min Qt version is 5.12 the birthTime property was introduced in Qt 5.10.
> Pay attention to the version numbers in the Build instructions of the README.md

Ok, I see, so I guess there is no easy way to build on 32 bit Ubuntu, since Qt in the official repo is 5.9.5. There is an older version of Minitube package in the repo, but it is not working.

**Comment by oasiscorpmse** [comment]
> 

Hi Mikhail,

Did you ever find a solution to your Minitube compilation issue for your 32-bit installation?  I'm running Linux Mint on my 32-bit eee PC and I encountered the same issue while trying to compile Minitube.  :(

**Comment by flaviotordini** [comment]
Problem is not 32bit but old Qt version. birthTime() was introduced in Qt 5.10.

**Comment by oasiscorpmse** [comment]
> Problem is not 32bit but old Qt version. birthTime() was introduced in Qt 5.10.

Hi Flavio,

Thank you for your reply.  I do realize that my installed Qt version is the problem, I'm just having trouble overcoming the issue.  I did try cloning the QT 5.15.5 repository from Github and compiled the source code on my 32-bit machine (it ran for an entire day), but for some reason my installation is still pointing to Qt version 5.9.5 instead of the newer 5.15.5 version.  I'm new to Qt, so I'm not sure how to fix this problem yet and was just curious is Mikhail, or someone else, might how discovered an easier solution.  Regardless, thank you again for your reply.
