### ISSUE TITLE
minitube fails to build with mpv 0.35

### ISSUE THREAD

**Issue by yurivict** [flaviotordini/minitube#229]
Regressed by http://github.com/mpv-player/mpv/commit/632059816add. Can you provide a fix or ask upstream? Otherwise, this port will be marked BROKEN or switched to mpv034 (port fork).

lib/media/src/mpv/mpvwidget.cpp:33:67: error: excess elements in struct initializer
    mpv_opengl_init_params gl_init_params{get_proc_address, this, nullptr};
                                                                  ^~~~~~~

Downstream report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267115
